# Generated by Django 3.2.23 on 2023-11-07 05:03

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 7, 5, 3, 51, 72469, tzinfo=utc), verbose_name='Дата добавления'),
        ),
        migrations.AlterField(
            model_name='castomuser',
            name='first_name',
            field=models.CharField(max_length=254, unique=True, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='castomuser',
            name='last_name',
            field=models.CharField(max_length=254, unique=True, verbose_name='Фамилия'),
        ),
    ]
