# Generated by Django 4.2.5 on 2023-11-08 03:38

import catalog.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_auto_20231107_0506'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='photo_file',
            field=models.ImageField(max_length=254, upload_to='image/', validators=[catalog.models.Application.validate_image, django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'bmp'])]),
        ),
    ]
